FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends libstdc++6 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY target/*-runner /app/app
RUN chmod +x /app/app

CMD ["/app/app"]
