apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: 80
  selector:
    app: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: DB_URL
              value: jdbc:postgresql://db2:5432/curso_springboot
            - name: DB_USERNAME
              value: devdb
            - name: DB_PASSWORD
              value: a1b2c3d4
            - name: JPA_DDL
              value: create-drop
          
          # readinessProbe:
          #   httpGet:
          #     path /actuator/health
          #     port: 80:80
          #   initialDelaySeconds: 10
          #   periodSeconds: 5